 /*
 * Inputs for D-LPEL on the SCC
 */


#define MASTER 0
#define NR_WORKERS 2 
#define POWER_DOMAIN 1
#define POWER_DOMAIN_WORKERS 8
#define MEMORY_DOMAIN 0
#define MEMORY_DOMAIN_WORKERS 10
#define LUT_MEMORY_DOMAIN_OFFSET 6
#define AIR_LUT_SYNCH_VALUE 1

